spring:
  config:
    import: optional:configserver:http://localhost:8890
  application:
    name: student-gateway
server:
  port: 8810
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
  zipkin:
    baseUrl: http://localhost:9411/
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: student-info
              uri: lb://student-info
              predicates:
                - Path=/api/student/**
            - id: student-subjects
              predicates:
                - Path=/api/subject/**
              uri: lb://student-subjects
            - id: student-analytical
              predicates:
                - Path=/api/calculate/**









